title: Aeon API
description: Complete API documentation for Aeon video creation and AIGC image processing
remote_theme: just-the-docs/just-the-docs

# Just-the-docs configuration
color_scheme: dark
search_enabled: true
heading_anchors: true

# Navigation structure
nav_order: 1

# Enable back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Documentation © 2025 Aeon. Released under the MIT License."

# Exclude files from being published to GitHub Pages
exclude:
  - private/
  - drafts/
  - internal-notes.md
  - "*.private.md"
  - dev-notes/
  - README.md  # if you don't want README shown on the site
